language: Python

compiler:
    - gcc
    
sudo: false

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.9
            - g++-4.9
            - python3
            - python3-numpy
            - python3-scipy
            - 

install:
    - wget http://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz 
    - tar xf cmake-3.3.2-Linux-x86_64.tar.gz
script:
    - export CC=/usr/bin/gcc-4.9
    - export CXX=/usr/bin/g++-4.9
    - cmake-3.3.2-Linux-x86_64/bin/cmake .
    - cmake-3.3.2-Linux-x86_64/bin/cmake --build . --target testit
    - cmake-3.3.2-Linux-x86_64/bin/cmake --build . --target benchmark
