language: python

python:
    - "3.4"
 
sudo: false

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.9
            - g++-4.9

install:
    - pip3 install numpy
    - pip3 install scipy
    - pip3 install setuptools
    - pip3 install cython 

script:
    - export CC=/usr/bin/gcc-4.9
    - export CXX=/usr/bin/g++-4.9
    - python3 setup.py develop --user
    - python3 -mraam.test
