language: python

python:
    - "3.4"
 
sudo: false

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.9
            - g++-4.9
            - python3
            - python3-numpy
            - python3-scipy
            - python3-pip 
            - python3-setuptools

install:
    - pip3 install cython --user

script:
    - export CC=/usr/bin/gcc-4.9
    - export CXX=/usr/bin/g++-4.9
    - ./setup.py develop --user
    - python3 -mraam.test
