language: python

python:
    - "3.4"
 
sudo: false

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.9
            - g++-4.9
            - libboost-test-dev

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update --yes conda

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy cython setuptools
    - wget --no-check-certificate http://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz 
    - tar xf cmake-3.3.2-Linux-x86_64.tar.gz

script:
    - export CC=/usr/bin/gcc-4.9
    - export CXX=/usr/bin/g++-4.9
    - cd craam
    - ../cmake-3.3.2-Linux-x86_64/bin/cmake . 
    - ../cmake-3.3.2-Linux-x86_64/bin/cmake --build . --target craam
    - cd ..
    - python3 setup.py install 
    - mkdir test_dir
    - cd test_dir
    - python3 -mraam.test
