language: python

python:
    - "3.4"
 
sudo: false

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.9
            - g++-4.9

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy cython setuptools

script:
    - export CC=/usr/bin/gcc-4.9
    - export CXX=/usr/bin/g++-4.9
    - python3 setup.py install
    - python3 -mraam.test
